### ISSUE TITLE
Every second startup fails: No module named 'pyasn1.compat.octets'

### ISSUE THREAD

**Issue by gavanfantom** [jaroschek/home-assistant-eaton-epdu#22]
Ever since upgrading to Home Assistant 2024.10, and continuing with 2024.10.1, every second restart of Home Assistant has resulted in the following error:

```Logger: homeassistant.setup
Source: setup.py:334
First occurred: 11:55:46 (1 occurrences)
Last logged: 11:55:46

Setup failed for custom integration 'eaton_epdu': Unable to import component: No module named 'pyasn1.compat.octets'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eaton_epdu/__init__.py", line 5, in <module>
    from homeassistant.components.snmp import async_get_snmp_engine
  File "/usr/src/homeassistant/homeassistant/components/snmp/__init__.py", line 3, in <module>
    from .util import async_get_snmp_engine
  File "/usr/src/homeassistant/homeassistant/components/snmp/util.py", line 7, in <module>
    from pysnmp.hlapi.asyncio import (
  File "/usr/local/lib/python3.12/site-packages/pysnmp/hlapi/asyncio/__init__.py", line 8, in <module>
    from pysnmp.proto.rfc1902 import *
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1902.py", line 8, in <module>
    from pysnmp.proto import rfc1155, error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1155.py", line 10, in <module>
    from pysnmp.proto import error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/error.py", line 9, in <module>
    from pysnmp import debug
  File "/usr/local/lib/python3.12/site-packages/pysnmp/debug.py", line 8, in <module>
    from pyasn1.compat.octets import octs2ints
ModuleNotFoundError: No module named 'pyasn1.compat.octets'

**Comment by jaroschek** [comment]
@gavanfantom This seems to be related to https://github.com/home-assistant/core/issues/125286.

I had theses issues reportd at https://github.com/jaroschek/home-assistant-eaton-ups/issues/32 too.

Therefor I made some requirement fixes and released theses as https://github.com/jaroschek/home-assistant-eaton-epdu/releases/tag/1.1.2

Did you already update to this version?

**Comment by gavanfantom** [comment]
I hadn't, as it hadn't filtered through HACS and been offered yet. I don't know how I missed the open issue too, sorry for that!

I can confirm that the new version does now fix the issue. Thank you!

**Comment by jaroschek** [comment]
I'm glad your problem could be solved so quick. :)

**Comment by evanrich** [comment]
With 1.1.2 and 2024.10.3 verison of HA, this still seems to be an issue:

```
# Clone eaton pdu repo
          [ ! -d "/config/repos/home-assistant-eaton-epdu" ] && git clone --branch 1.1.2 https://github.com/jaroschek/home-assistant-eaton-epdu.git
          [ ! -L "/config/custom_components/eaton_epdu" ] && ln -s /config/repos/home-assistant-eaton-epdu/custom_components/eaton_epdu /config/custom_components/eaton_epdu
```
i have that in an init container to pull the repo,  and then when home assistant starts, i see the following in logs:
 ```
ModuleNotFoundError: No module named 'pyasn1.compat.octets'
2024-10-20 19:39:35.572 ERROR (MainThread) [homeassistant.config] Platform error: sensor - No module named 'pyasn1.compat.octets'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config.py", line 1413, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1100, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1195, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
```

can confirm 1.1.2 is loaded:
![image](https://github.com/user-attachments/assets/69348b52-ba9a-4d07-8b1f-7e8406be3df8)

![image](https://github.com/user-attachments/assets/73f267ac-00ab-4d72-9121-1aaf16796e79)
